version: "3"
services:
  app:
    build: 
        context: .docker/php
        args:
            UID: $U_ID
    container_name: learn-symfony.app
    ports:
        - "9010:80"
    environment:
        PHP_IDE_CONFIG: "serverName=Docker"
        PHP_XDEBUG_ENABLED: 1
        XDEBUG_CONFIG: remote_host=172.17.0.1 remote_port=9005
    volumes:
        - .:/appdata/www
        - .docker/php/xdebug-linux.ini:/usr/local/etc/php/conf.d/xdebug.ini
    depends_on:
        - mysql

  mysql:
    image: mysql:8.0
    container_name: learn-symfony.mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: 1234
    ports:
        - "9011:3306"
        